# Generated by Django 2.2.10 on 2020-05-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersicerik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesajdersogrenci',
            name='dersicerik',
        ),
        migrations.RenameField(
            model_name='dersicerikmezun',
            old_name='adres',
            new_name='aciklama',
        ),
        migrations.RemoveField(
            model_name='dersicerikmezun',
            name='telefon',
        ),
        migrations.AddField(
            model_name='dersicerikmezun',
            name='dersAdi',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dersicerikmezun',
            name='ogretimGorevlisi',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='dersicerikOgrenci',
        ),
        migrations.DeleteModel(
            name='MesajdersOgrenci',
        ),
    ]
