# Generated by Django 2.2.10 on 2020-05-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dersicerik', '0002_auto_20200521_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersicerikmezun',
            name='teslimTarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
