# Generated by Django 2.2.12 on 2020-05-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranskriptMezun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=250)),
                ('soyad', models.CharField(max_length=250)),
                ('tc', models.CharField(max_length=11)),
                ('ogrenciNo', models.IntegerField(default=None)),
                ('mezunYili', models.IntegerField()),
                ('telefon', models.CharField(max_length=11)),
                ('adres', models.TextField(max_length=250)),
                ('istekTarihi', models.DateTimeField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TranskriptOgrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=250)),
                ('soyad', models.CharField(max_length=250)),
                ('tc', models.CharField(max_length=11)),
                ('ogrenciNo', models.IntegerField()),
                ('telefon', models.CharField(max_length=11)),
                ('adres', models.TextField(max_length=250)),
                ('istekTarihi', models.DateTimeField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
