# Generated by Django 2.2.12 on 2020-05-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belgeler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transkriptmezun',
            name='ogrenciNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
