# Generated by Django 2.2.12 on 2020-05-08 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belgeler', '0003_mesajmezun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesajmezun',
            name='transkript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajMezun', to='belgeler.TranskriptMezun'),
        ),
    ]
