# Generated by Django 2.2.12 on 2020-05-08 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('belgeler', '0005_mesajogrenci'),
    ]

    operations = [
        migrations.AddField(
            model_name='transkriptmezun',
            name='teslimTarihi',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 5, 22, 49, 738853, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transkriptogrenci',
            name='teslimTarihi',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 5, 22, 54, 245657, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
