# Generated by Django 2.2.12 on 2020-05-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belgeler', '0006_auto_20200508_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesajogrenci',
            name='belge',
            field=models.FileField(blank=True, null=True, upload_to='media/belgeler'),
        ),
    ]
