# Generated by Django 2.2.12 on 2020-05-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belgeler', '0008_auto_20200509_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesajmezun',
            name='belge',
            field=models.FileField(blank=True, null=True, upload_to='belgeler'),
        ),
    ]
