# Generated by Django 2.2.12 on 2020-05-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belgeler', '0009_auto_20200509_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transkriptmezun',
            name='teslimTarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transkriptogrenci',
            name='teslimTarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
