# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-28 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stajilani',
            name='stajIlanTarihi',
            field=models.DateTimeField(),
        ),
    ]
