# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-28 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200428_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isilaniekle',
            name='ilanTarihi',
            field=models.DateTimeField(),
        ),
    ]
