# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-02 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dersNotu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ders',
            name='content',
        ),
        migrations.RemoveField(
            model_name='ders',
            name='title',
        ),
    ]
