# Generated by Django 2.2.12 on 2020-05-15 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesajOgrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('mesaj', models.TextField()),
                ('mesajTarihi', models.DateTimeField(auto_now_add=True)),
                ('transkript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajOgrenci', to='randevu.randevuOgrenci')),
            ],
        ),
        migrations.CreateModel(
            name='MesajMezun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('mesaj', models.TextField()),
                ('mesajTarihi', models.DateTimeField(auto_now_add=True)),
                ('transkript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajMezun', to='randevu.randevuMezun')),
            ],
        ),
    ]
