# Generated by Django 2.2.12 on 2020-05-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0005_auto_20200516_2104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MesajMezun',
            new_name='MesajRandevuMezun',
        ),
        migrations.RenameModel(
            old_name='MesajOgrenci',
            new_name='MesajRandevuOgrenci',
        ),
    ]
