# Generated by Django 2.2.12 on 2020-05-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0006_auto_20200516_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesajrandevumezun',
            name='belge',
            field=models.FileField(blank=True, null=True, upload_to='belgeler'),
        ),
        migrations.AddField(
            model_name='mesajrandevuogrenci',
            name='belge',
            field=models.FileField(blank=True, null=True, upload_to='belgeler'),
        ),
    ]
