# Generated by Django 2.2.10 on 2020-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0007_auto_20200516_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevumezun',
            name='ogretimGorevlisi',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='randevuogrenci',
            name='ogretimGorevlisi',
            field=models.EmailField(max_length=254),
        ),
    ]
