# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-20 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mezun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrenimDurumu', models.CharField(max_length=7)),
                ('ogrenciNo', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('telefonNumarasi', models.CharField(max_length=120)),
                ('cinsiyet', models.CharField(max_length=7)),
                ('sehir', models.CharField(max_length=255)),
                ('adres', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogrenimDurumu', models.CharField(max_length=7)),
                ('ogrenciNo', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('telefonNumarasi', models.CharField(max_length=120)),
                ('cinsiyet', models.CharField(max_length=7)),
                ('sehir', models.CharField(max_length=255)),
                ('adres', models.CharField(max_length=300)),
                ('gorulenStajId', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
