# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-28 02:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='oncekiGiris',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 2, 22, 50, 49819, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
