# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-28 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200429_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='gorulenIsId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
