# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-28 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ogrenci_gorulenisid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='ilanToplam',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
