# Generated by Django 2.2.12 on 2020-05-03 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200502_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezun',
            name='oncekiGirisIs',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 4, 12, 42, 113205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mezun',
            name='oncekiGirisStaj',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 4, 12, 42, 113205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='oncekiGirisIs',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 4, 12, 42, 114233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='oncekiGirisStaj',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 4, 12, 42, 114233, tzinfo=utc)),
        ),
    ]
