# Generated by Django 2.2.12 on 2020-05-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200503_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezun',
            name='oncekiGirisIs',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mezun',
            name='oncekiGirisStaj',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='oncekiGirisIs',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='oncekiGirisStaj',
            field=models.DateTimeField(),
        ),
    ]
