# Generated by Django 2.2.12 on 2020-05-07 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bolumsekreteri_ogretimgorevlisi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolumsekreteri',
            old_name='gorulenTrankript',
            new_name='gorulenTranskript',
        ),
    ]
