# Generated by Django 2.2.12 on 2020-05-08 02:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200507_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezun',
            name='gorulenTranskript',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mezun',
            name='oncekiGirisTranskript',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 2, 5, 19, 909082, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='gorulenTranskript',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='oncekiGirisTranskript',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 2, 5, 36, 745608, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
