# Generated by Django 2.2.12 on 2020-05-09 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200509_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolumsekreteri',
            old_name='oncekiGirisTranskript',
            new_name='oncekiGirisTranskriptMezun',
        ),
        migrations.AddField(
            model_name='bolumsekreteri',
            name='oncekiGirisTranskriptOgrenci',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 10, 0, 7, 50086, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
