# Generated by Django 2.2.12 on 2020-05-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200509_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolumsekreteri',
            name='gorulenTranskript',
            field=models.IntegerField(default=0),
        ),
    ]
