# Generated by Django 2.2.12 on 2020-05-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200509_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezun',
            name='ogrenimDurumu',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
