# Generated by Django 2.2.12 on 2020-05-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200509_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezun',
            name='adres',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mezun',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mezun',
            name='cinsiyet',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='mezun',
            name='sehir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mezun',
            name='telefonNumarasi',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
