# Generated by Django 2.2.12 on 2020-05-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200510_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezun',
            name='ogrenciNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
