# Generated by Django 2.2.12 on 2020-05-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_mezun_ogrencino'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezun',
            name='ogrenciNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
