# Generated by Django 2.2.12 on 2020-05-09 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_mezun_ogrencino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mezun',
            name='ogrenciNo',
        ),
    ]
