# Generated by Django 2.2.12 on 2020-05-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_mezun_ogrencino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mezun',
            name='ulke',
        ),
    ]
