# Generated by Django 2.2.12 on 2020-05-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200516_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezun',
            name='gorulenRandevu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mezun',
            name='oncekiGirisRandevu',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='gorulenRandevu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='oncekiGirisRandevu',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ogretimgorevlisi',
            name='gorulenRandevu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ogretimgorevlisi',
            name='gorulenRandevuMezun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ogretimgorevlisi',
            name='gorulenRandevuOgrenci',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ogretimgorevlisi',
            name='oncekiGirisRandevuMezun',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ogretimgorevlisi',
            name='oncekiGirisRandevuOgrenci',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
