# Generated by Django 2.2.12 on 2020-05-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200516_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezun',
            name='gorulenDersIcerik',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mezun',
            name='oncekiGirisDersIcerik',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='gorulenDersIcerik',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ogrenci',
            name='oncekiGirisDersIcerik',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ogretimgorevlisi',
            name='gorulenDersIcerik',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ogretimgorevlisi',
            name='gorulenDersIcerikMezun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ogretimgorevlisi',
            name='gorulenDersIcerikOgrenci',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ogretimgorevlisi',
            name='oncekiGirisDersIcerikMezun',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ogretimgorevlisi',
            name='oncekiGirisDersIcerikOgrenci',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
